import React, {useEffect} from "react";
import WideBlock from "../../blocks/wideBlock";
import SmallBlock from "../../blocks/smallBlock";
import MiddleBlock from "../../blocks/middleBlock";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);
const AllInset = ({onSelectCase, process}) => {
    useEffect(() => {
        ScrollTrigger.refresh(); 
    }, [])
    return (
        <>
            <WideBlock  
                process={process}
                image={"illustration/sber.jpg"}
                imageMin={"illustration/sber-min.jpg"}
                alt={"sber"}
                classes={"cases__filter--salad"}
                description={"Development of architectural stylistics, modeling and visualization of an interactive map for an online exhibition"}
                pageName={"sber"}
                caseName={"Sberbank"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"branding/hydra.jpg"}
                imageMin1={"branding/hydra-min.jpg"}
                alt1={"hydra"}
                classes1={"cases__filter--sky-blue"}
                description1={"Rebranding of the Hydra company with a change in the logo, style and presentation design"}
                pageName1={"hydra"}
                caseName1={"Hydra"}
                image2={"branding/scalar.jpg"}
                imageMin2={"branding/scalar-min.jpg"}
                alt2={"scalar"}
                classes2={"cases__filter--scalar-brand"}
                description2={"Development of a logo, corporate identity, brand book, smm, site for Scalar company"}
                pageName2={"scalar-brand"}
                caseName2={"Scalar"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"branding/nabatu.jpg"}
                imageMin1={"branding/nabatu-min.jpg"}
                alt1={"nabatu"}
                classes1={"cases__filter--beige"}
                description1={"Development of a logo and corporate identity for a city coffee shop “Nabatu”"}
                pageName1={"nabatu"}
                caseName1={"Nabatu"}
                image2={"branding/urban.jpg"}
                imageMin2={"branding/urban-min.jpg"}
                alt2={"urban"}
                classes2={"cases__filter--green"}
                description2={"Logo and corporate identity for an event company specializing in sports events"}
                pageName2={"urban-farm"}
                caseName2={"Urban Farm"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"digital/event-producer.jpg"}
                imageMin1={"digital/event-producer-min.jpg"}
                alt1={"event-producer"}
                classes1={"cases__filter--black"}
                description1={"Website development for an event producer"}
                pageName1={"shapoval"}
                caseName1={"Shapoval"}
                image2={"digital/vrspace.jpg"}
                imageMin2={"digital/vrspace-min.jpg"}
                alt2={"vrspace"}
                classes2={"cases__filter--vrspace"}
                description2={"Website for the viar spaces developer company"}
                pageName2={"vr-space"}
                caseName2={"Vr-space"}
                onSelectCase={onSelectCase}
                />
            <MiddleBlock 
                process={process}
                image1={"digital/dronico.jpg"}
                imageMin1={"digital/dronico-min.jpg"}
                alt1={"dronico"}
                classes1={"cases__filter--dronico"}
                description1={"Dronico company website"}
                pageName1={"dronico"}
                caseName1={"Dronico"}
                image2={"digital/legend.jpg"}
                imageMin2={"digital/legend-min.jpg"}
                alt2={"legend"}
                classes2={"cases__filter--black"}
                description2={"Website of the event company Legend"}
                pageName2={"legend"}
                caseName2={"Legend"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"enviroment/saldens.jpg"}
                imageMin1={"enviroment/saldens-min.jpg"}
                alt1={"saldens"}
                classes1={"cases__filter--saldens"}
                description1={"Design and planning solutions for Saldens confectionery"}
                pageName1={"saldens"}
                caseName1={"Saldens"}
                image2={"enviroment/cafeteria.jpg"}
                imageMin2={"enviroment/cafeteria-min.jpg"}
                alt2={"cafeteria"}
                classes2={"cases__filter--cafeteria"}
                description2={"Design and planning solutions for the city cafeteria"}
                pageName2={"cafeteria"}
                caseName2={"Cafeteria"}
                onSelectCase={onSelectCase}
                />
            <MiddleBlock 
                process={process}
                image1={"enviroment/interrior.jpg"}
                imageMin1={"enviroment/interrior-min.jpg"}
                alt1={"interrior"}
                classes1={"cases__filter--interrior"}
                description1={"Concept development and visualization of interior solutions for the residential complex Dream"}
                pageName1={"interrior"}
                caseName1={"Dream Interrior"}
                image2={"enviroment/urban.jpg"}
                imageMin2={"enviroment/urban-min.jpg"}
                alt2={"urban"}
                classes2={"cases__filter--urban"}
                description2={"Design concept of urban coworking space"}
                pageName2={'urban'}
                caseName2={"Urban"}
                onSelectCase={onSelectCase}/>
            <SmallBlock     
                process={process}
                image1={"illustration/structure-min.jpg"}
                imageMin1={"illustration/structure-min.jpg"}
                alt1={"structure"}
                classes1={"cases__filter--dark-orange"}
                description1={" Creating a series of 3D illustrations for the presentation of the company Structure"}
                pageName1={"structura"}
                caseName1={"Structura"}
                image2={"illustration/rightstep.jpg"}
                imageMin2={"illustration/rightstep-min.jpg"}
                alt2={"rightstep"}
                classes2={"cases__filter--dark-yellow"}
                description2={"Development of a visual concept and rendering of 3d illustrations for the rightstep company website"}
                pageName2={"rightstep"}
                caseName2={"RightStep"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock    
                process={process}
                image1={"illustration/circle.jpg"}
                imageMin1={"illustration/circle-min.jpg"}
                alt1={"circle"}
                classes1={"cases__filter--dark-sky"}
                description1={" Creating infographics and product visualizations for Сirclegen's website"}
                pageName1={"circle-illustration"}
                caseName1={"Circle"}
                image2={"illustration/genesis.jpg"}
                imageMin2={"illustration/genesis-min.jpg"}
                alt2={"genesis"}
                classes2={"cases__filter--genesis"}
                description2={"Creating an interactive animated illustration of the city of the future for the Genesis Engeniring company website"}
                pageName2={"genesis"}
                caseName2={"Genesis"}
                onSelectCase={onSelectCase}/>
             <SmallBlock 
                process={process}
                image1={"presentations/azot.jpg"}
                imageMin1={"presentations/azot.jpg"}
                alt1={"azot"}
                classes1={"cases__filter--cors"}
                description1={"Development of a multilingual corporate report for the international company Shchekinoazot"}
                pageName1={"shchekinoazot"}
                caseName1={"Shchekinoazot"}
                image2={"presentations/structure.jpg"}
                imageMin2={"presentations/structure-min.jpg"}
                alt2={"structure"}
                classes2={"cases__filter--structure"}
                description2={"A series of presentations of various activities of the event company “Structure”"}
                pageName2={"structura-prez"}
                caseName2={"Structura Prezentation"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"presentations/elephant.jpg"}
                imageMin1={"presentations/elephant-min.jpg"}
                alt1={"elephant"}
                classes1={"cases__filter--elephant"}
                description1={"Development of the presentation of an international circus show"}
                pageName1={"elephant"}
                caseName1={"Elephant"}
                image2={"presentations/zvezda.jpg"}
                imageMin2={"presentations/zvezda-min.jpg"}
                alt2={"zvezda"}
                classes2={"cases__filter--zvezda"}
                description2={"Presentation of event sites for tenants"}
                pageName2={"zvezda"}
                caseName2={"Zvezda"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"branding/marevna.jpg"}
                imageMin1={"branding/marevna-min.jpg"}
                alt1={"marevna"}
                classes1={"cases__filter--black"}
                description1={"Branding of the Marevna company"}
                pageName1={"marevna"}
                caseName1={"Marevna"}
                image2={"branding/cloth.jpg"}
                imageMin2={"branding/cloth-min.jpg"}
                alt2={"cloth"}
                classes2={"cases__filter--blue"}
                description2={"Development of a logo, corporate identity, packaging and interior for an urban clothing brand K/CHT/Z"}
                pageName2={"k-cht-z"}
                caseName2={"K Cht Z"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"branding/Irus.jpg"}
                imageMin1={"branding/Irus-min.jpg"}
                alt1={"Irus"}
                classes1={"cases__filter--dark-blue"}
                description1={"Logo and visual style for the real estate developer Irus"}
                pageName1={"irus"}
                caseName1={"Irus"}
                image2={"branding/n13.jpg"}
                imageMin2={"branding/n13-min.jpg"}
                alt2={"n13"}
                classes2={"cases__filter--light-gray"}
                description2={"Logo and packaging for streetwear brand No. 13"}
                pageName2={"n-13"}
                caseName2={"№ 13"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"digital/tenet.jpg"}
                imageMin1={"digital/tenet-min.jpg"}
                alt1={"tenet"}
                classes1={"cases__filter--tenet"}
                description1={"Landing page for the Tenet blockchain project"}
                pageName1={"tenet"}
                caseName1={"Tenet"}
                image2={"digital/google-event.jpg"}
                imageMin2={"digital/google-event-min.jpg"}
                alt2={"google-event"}
                classes2={"cases__filter--google-event"}
                description2={"Website for an internal corporate event of Google"}
                pageName2={"google"}
                caseName2={"Google"}
                onSelectCase={onSelectCase}
                />
            <MiddleBlock 
                process={process}
                image1={"digital/google.jpg"}
                imageMin1={"digital/google-min.jpg"}
                alt1={"google"}
                classes1={"cases__filter--black"}
                description1={"Website for an internal corporate event of Google"}
                pageName1={"google-games"}
                caseName1={"Google think games"}
                image2={"digital/pergamon.jpg"}
                imageMin2={"digital/pergamon-min.jpg"}
                alt2={"pergamon"}
                classes2={"cases__filter--pergamon"}
                description2={"Website of the non-commercial Historical Foundation Pergamon"}
                pageName2={"pergamon"}
                caseName2={"Pergamon"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"enviroment/exeed.jpg"}
                imageMin1={"enviroment/exeed-min.jpg"}
                alt1={"exeed"}
                classes1={"cases__filter--exeed"}
                description1={"Design and visualization of the car stand of Exeed brand cars"}
                pageName1={'exeed'}
                caseName1={"Exeed"}
                image2={"enviroment/porsche.jpg"}
                imageMin2={"enviroment/porsche-min.jpg"}
                alt2={"porsche"}
                classes2={"cases__filter--porsche"}
                description2={"Design and visualization of a family event dedicated to the 70th anniversary of the Porsche company"}
                pageName2={'porsche'}
                caseName2={"Porsche"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"enviroment/toyota.jpg"}
                imageMin1={"enviroment/toyota-min.jpg"}
                alt1={"toyota"}
                classes1={"cases__filter--toyota2"}
                description1={"Design and visualization of the Toyota event space concept"}
                pageName1={"toyota"}
                caseName1={"Toyota"}
                image2={"enviroment/kiosk.jpg"}
                imageMin2={"enviroment/kiosk-min.jpg"}
                alt2={"kiosk"}
                classes2={"cases__filter--black"}
                description2={"Interior design of a cafe with Israeli street fast food"}
                pageName2={"kiosk"}
                caseName2={"Kiosk"}
                onSelectCase={onSelectCase}/>
            <SmallBlock     
                process={process}
                image1={"illustration/complex.jpg"}
                imageMin1={"illustration/complex-min.jpg"}
                alt1={"complex"}
                classes1={"cases__filter--yellow-brown"}
                description1={"Visualization of the layout of the building of the scientific complex"}
                pageName1={"3d-map"}
                caseName1={"3D Map"}
                image2={"illustration/paveletsky.jpg"}
                imageMin2={"illustration/paveletsky-min.jpg"}
                alt2={"paveletsky"}
                classes2={"cases__filter--pav"}
                description2={"Modeling and floor-by-floor rendering of spaces and interiors of the event site"}
                pageName2={"paveletsky"}
                caseName2={"Paveletsky"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock    
                process={process}
                image1={"illustration/creative.jpg"}
                imageMin1={"illustration/creative-min.jpg"}
                alt1={"creative"}
                classes1={"cases__filter--black"}
                description1={"Development of illustrations for the digital agency website"}
                pageName1={"creative"}
                caseName1={"Creative Communication"}
                image2={"illustration/3d.jpg"}
                imageMin2={"illustration/3d-min.jpg"}
                alt2={"illustration/3d"}
                classes2={"cases__filter--three"}
                description2={"3d illustration series for websites"}
                pageName2={'3d-illustration'}
                caseName2={"3D Illustration"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"presentations/fest.jpg"}
                imageMin1={"presentations/fest-min.jpg"}
                alt1={"fest"}
                classes1={"cases__filter--fest"}
                description1={"Sponsored presentation of the music festival"}
                pageName1={"fest"}
                caseName1={"Fest"}
                image2={"presentations/promomed.jpg"}
                imageMin2={"presentations/promomed-min.jpg"}
                alt2={"promomed"}
                classes2={"cases__filter--promomed"}
                description2={"Development of a universal corporate template for the pharmaceutical company “Promomed”"}
                pageName2={"promomed"}
                caseName2={"Promomed"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"presentations/beyond.jpg"}
                imageMin1={"presentations/beyond-min.jpg"}
                alt1={"beyond"}
                classes1={"cases__filter--beyond"}
                description1={"Presentation of a marketing company about services and competencies"}
                pageName1={"beyond"}
                caseName1={"Beyond"}
                image2={"presentations/ozon.jpg"}
                imageMin2={"presentations/ozon-min.jpg"}
                alt2={"ozon"}
                classes2={"cases__filter--ozon"}
                description2={"A series of training presentations for employees and partners"}
                pageName2={"ozon"}
                caseName2={"Ozon"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"branding/style.jpg"}
                imageMin1={"branding/style-min.jpg"}
                alt1={"style"}
                classes1={"cases__filter--purple"}
                description1={"Logo and corporate identity for an event company specializing in sports events"}
                pageName1={"style-project"}
                caseName1={"Style"}
                image2={"branding/dream.jpg"}
                imageMin2={"branding/dream-min.jpg"}
                alt2={"dream"}
                classes2={"cases__filter--orange"}
                description2={"Logo, corporate identity, presentation materials and interiors for the residential complex 'Dream'"}
                pageName2={"dream"}
                caseName2={"Dream"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"branding/seafood.jpg"}
                imageMin1={"branding/seafood-min.jpg"}
                alt1={"seafood"}
                classes1={"cases__filter--blue"}
                description1={"Seafood catering company for the preparation and delivery of ready meals for events"}
                pageName1={"sea-food"}
                caseName1={"Sea Food"}
                image2={"branding/circle.jpg"}
                imageMin2={"branding/circle-min.jpg"}
                alt2={"circle"}
                classes2={"cases__filter--gray2"}
                description2={"Development of a logo and presentation materials for the company Circle gen"}
                pageName2={"circle"}
                caseName2={"Circle"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"digital/step-network.jpg"}
                imageMin1={"digital/step-network-min.jpg"}
                alt1={"step-network"}
                classes1={"cases__filter--step-network"}
                description1={"The website of the blockchain project of the Step Network company"}
                pageName1={"step-launchpad"}
                caseName1={"Step launchpad"}
                image2={"digital/alus.jpg"}
                imageMin2={"digital/alus-min.jpg"}
                alt2={"alus"}
                classes2={"cases__filter--alus"}
                description2={"Development of the website of the company Alus"}
                pageName2={"alus"}
                caseName2={"Alus"}
                onSelectCase={onSelectCase}
                />
            <MiddleBlock 
                process={process}
                image1={"digital/blockchein.jpg"}
                imageMin1={"digital/blockchein-min.jpg"}
                alt1={"blockchein"}
                classes1={"cases__filter--blockchein"}
                description1={"The website of the blockchain project"}
                pageName1={"step-network"}
                caseName1={"Step network"}
                image2={"digital/skillbox.jpg"}
                imageMin2={"digital/skillbox-min.jpg"}
                alt2={"skillbox"}
                classes2={"cases__filter--skillbox"}
                description2={"Development of interfaces for digital games"}
                pageName2={"skillbox"}
                caseName2={"Skillbox"}
                onSelectCase={onSelectCase}/>
            <SmallBlock     
                process={process}
                image1={"illustration/gift.jpg"}
                imageMin1={"illustration/gift-min.jpg"}
                alt1={"gift"}
                classes1={"cases__filter--gift"}
                description1={"Creating a creative concept and drawing a series of illustrations for a gift calendar"}
                pageName1={'calendar'}
                caseName1={"Calendar"}
                image2={"illustration/field-day.jpg"}
                imageMin2={"illustration/field-day-min.jpg"}
                alt2={"field-day"}
                classes2={"cases__filter--field"}
                description2={"Creating an animated interactive map for an online exhibition of achievements"}
                pageName2={"field-day"}
                caseName2={"Field Day"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock    
                process={process}
                image1={"illustration/scalar.jpg"}
                imageMin1={"illustration/scalar-min.jpg"}
                alt1={"scalar"}
                classes1={"cases__filter--scalar"}
                description1={"Creating a concept and drawing a series of illustrations for the Scalar company website"}
                pageName1={"scalar"}
                caseName1={"Scalar"}
                image2={"illustration/smart.jpg"}
                imageMin2={"illustration/smart-min.jpg"}
                alt2={"smart"}
                classes2={"cases__filter--smart"}
                description2={"3d illustration series for  websites"}
                pageName2={"smart"}
                caseName2={"Smart"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"presentations/toyota.jpg"}
                imageMin1={"presentations/toyota-min.jpg"}
                alt1={"toyota"}
                classes1={"cases__filter--toyota"}
                description1={"Development of rules for the presentation of a new Toyota car"}
                pageName1={'toyota-prez'}
                caseName1={'Toyota Prezentation'}
                image2={"presentations/lamps.jpg"}
                imageMin2={"presentations/lamps-min.jpg"}
                alt2={"lamps"}
                classes2={"cases__filter--lamps"}
                description2={"Design of presentation of air show programs for Saudi Arabia"}
                pageName2={'dronico-presentation'}
                caseName2={'Dronico'}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"presentations/spirit.jpg"}
                imageMin1={"presentations/spirit-min.jpg"}
                alt1={"spirit"}
                classes1={"cases__filter--spirit"}
                description1={"Corporate presentation within the event program of Bakardi company"}
                pageName1={'spirit'}
                caseName1={'Spirit'}
                image2={"presentations/zen.jpg"}
                imageMin2={"presentations/zen-min.jpg"}
                alt2={"zen"}
                classes2={"cases__filter--zen"}
                description2={"Presentation for the speaker as part of the presentation of the Yandex company product"}
                pageName2={'zen'}
                caseName2={'Zen'}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"illustration/map.jpg"}
                imageMin1={"illustration/map-min.jpg"}
                alt1={"map"}
                pageName1={"map"}
                caseName1={"Map"}
                classes1={"cases__filter--map"}
                description1={"Creating an animated interactive map for an online exhibition of achievements"}
                image2={"enviroment/soul.jpg"}
                imageMin2={"enviroment/soul-min.jpg"}
                alt2={"soul"}
                classes2={"cases__filter--soul"}
                description2={"Design and visualization of the design concept of the platform for the presentation of the Porsche Taycan"}
                pageName2={"soul"}
                caseName2={"Soul"}
                onSelectCase={onSelectCase}/>
            <MiddleBlock 
                process={process}
                image1={"branding/wana-sari-mid.jpg"}
                imageMin1={"branding/wana-sari-min.jpg"}
                alt1={"wana-sari"}
                classes1={"cases__filter--dark-green"}
                description1={"Logo and corporate identity development for a home boutique hotel in Bali"}
                pageName1={"wana-sari"}
                caseName1={"Wana Sari"}
                image2={"enviroment/dream-mid.jpg"}
                imageMin2={"enviroment/dream-min.jpg"}
                alt2={"dream"}
                classes2={"cases__filter--dream"}
                description2={"Development of the concept and visualization of exterior solutions for the residential complex “Dream”"}
                pageName2={"dream-enviroment"}
                caseName2={"Dream Enviroment"}
                onSelectCase={onSelectCase}/>
            <SmallBlock 
                process={process}
                image1={"digital/factory-mid.jpg"}
                imageMin1={"digital/factory-min.jpg"}
                alt1={"factory"}
                classes1={"cases__filter--factory"}
                description1={"Website development for a company that develops software for factories and large enterprises"}
                pageName1={"rightstep-web"}
                caseName1={"Right step"}
                image2={"presentations/dimash-mid.jpg"}
                imageMin2={"presentations/dimash-min.jpg"}
                alt2={"dimash"}
                classes2={"cases__filter--dimash"}
                description2={"Sponsored presentation of the international concert tour dedicated to the new music album"}
                pageName2={"dimash"}
                caseName2={"Dimash"}
                onSelectCase={onSelectCase}/>
        </>
    )
}

export default AllInset;